/**
 * @file Automatically generated by barrelsby.
 */

export * from "src/predicates/new/getPreciseType";
export * from "src/predicates/new/isObjectOrArray";
export * from "src/predicates/new/extends-lodash/index";
