/**
 * @file Automatically generated by barrelsby.
 */

export * from "src/predicates/new/extends-lodash/isArgument";
export * from "src/predicates/new/extends-lodash/isArrayBuffer";
export * from "src/predicates/new/extends-lodash/isArrayLike";
export * from "src/predicates/new/extends-lodash/isArrayLikeObject";
export * from "src/predicates/new/extends-lodash/isBuffer";
export * from "src/predicates/new/extends-lodash/isElement";
export * from "src/predicates/new/extends-lodash/isEmpty";
export * from "src/predicates/new/extends-lodash/isEqual";
export * from "src/predicates/new/extends-lodash/isEqualWith";
export * from "src/predicates/new/extends-lodash/isFinite";
export * from "src/predicates/new/extends-lodash/isInteger";
export * from "src/predicates/new/extends-lodash/isLength";
export * from "src/predicates/new/extends-lodash/isMatch";
export * from "src/predicates/new/extends-lodash/isMatchWith";
export * from "src/predicates/new/extends-lodash/isNaN";
export * from "src/predicates/new/extends-lodash/isNative";
export * from "src/predicates/new/extends-lodash/isNil";
export * from "src/predicates/new/extends-lodash/isObjectLoose";
export * from "src/predicates/new/extends-lodash/isPlainObject";
export * from "src/predicates/new/extends-lodash/isSafeInteger";
export * from "src/predicates/new/extends-lodash/isSet";
export * from "src/predicates/new/extends-lodash/isTypedArray";
export * from "src/predicates/new/extends-lodash/isWeakMap";
