import fs from "fs";
import path from "path";

const targetDir = "./src";

console.log(`🕧 Removing Barrelsby is Starting`);

function removeBarrelsbyComment(filePath: string) {
  let content = fs.readFileSync(filePath, "utf-8");

  const barrelsbyCommentRegex =
    /\/\*\*\n\s*\*\s*@file Automatically generated by barrelsby\.\n\s*\*\/*/g;

  let newContent = content.replace(barrelsbyCommentRegex, "");

  newContent = newContent.replace(/^\s*\n*/, "");

  if (newContent !== content) {
    fs.writeFileSync(filePath, newContent, "utf-8");
    console.log(`🟢 Removed barrelsby comment from ${filePath}`);
  }
}

function walkDir(dir: string) {
  for (const file of fs.readdirSync(dir)) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      walkDir(fullPath);
    } else if (
      fullPath.endsWith("index.d.ts") ||
      fullPath.endsWith("index.ts") ||
      fullPath.endsWith("index.tsx") ||
      fullPath.endsWith("index.cjs") ||
      fullPath.endsWith("index.js")
    ) {
      removeBarrelsbyComment(fullPath);
    }
  }
}
walkDir(targetDir);

console.log(`\n✅ Removing Barrelsby Finish`);
