import chalk from "chalk";
import fs from "fs";
import path from "path";

const targetDir = "./src";

let barrelRemoved = 0;

console.log(
  chalk.bold(
    `🕧 ${chalk.cyanBright("Starting")} to ${chalk.underline.blueBright(
      "Removing Barrelsby"
    )} at ${chalk.italic.underline.whiteBright("'" + targetDir + "'")} folder.`
  )
);

function removeBarrelsbyComment(filePath: string) {
  let content = fs.readFileSync(filePath, "utf-8");

  const barrelsbyCommentRegex =
    /\/\*\*\n\s*\*\s*@file Automatically generated by barrelsby\.\n\s*\*\/*/g;

  let newContent = content.replace(barrelsbyCommentRegex, "");

  newContent = newContent.replace(/^\s*\n*/, "");

  if (newContent !== content) {
    fs.writeFileSync(filePath, newContent, "utf-8");
    // console.log(`🟢 Removed barrelsby comment from ${filePath}`);

    console.log(
      `${chalk.bold("   >")} ${chalk.italic(
        `${chalk.white(barrelRemoved + ".")} ${chalk.white(
          "Removing Barrelsby"
        )} ${chalk.cyan("in")} ${chalk.bold.underline.blueBright(filePath)}.`
      )}`
    );
  }
}

function walkDir(dir: string) {
  for (const [idx, file] of fs.readdirSync(dir).sort().entries()) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      walkDir(fullPath);
    } else if (
      fullPath.endsWith("index.d.ts") ||
      fullPath.endsWith("index.ts") ||
      fullPath.endsWith("index.tsx") ||
      fullPath.endsWith("index.cjs") ||
      fullPath.endsWith("index.js")
    ) {
      barrelRemoved++;
      removeBarrelsbyComment(fullPath);
    }
  }
}

walkDir(targetDir);

if (barrelRemoved > 0) {
  console.log(
    chalk.bold(
      `✅ ${chalk.greenBright("Success")} ${chalk.underline.blueBright(
        "Removing Barrelsby"
      )} (${chalk.yellowBright(
        `${barrelRemoved} file${barrelRemoved > 1 ? "(s)" : ""}`
      )}) at ${chalk.italic.underline.whiteBright("'" + targetDir + "'")} folder.`
    )
  );
} else {
  console.log(
    chalk.bold(
      `⚠️  ${chalk.yellowBright("Skipping")} ${chalk.underline.blueBright(
        "Removing Barrelsby"
      )} ${chalk.white("because")} ${chalk.redBright(
        "nothing left"
      )} files at ${chalk.italic.underline.whiteBright(
        "'dist'"
      )} folder to ${chalk.dim.redBright("injecting")}.`
    )
  );
}
